baseURL: 'https://hugo-profile.netlify.app'
languageCode: en-us
title: Hugo Profile
theme: hugo-profile
outputs:
  home:
    - HTML
    - RSS
    - JSON
  page:
    - HTML
    - RSS
Paginate: 3
enableRobotsTXT: true
markup:
  goldmark:
    renderer:
      unsafe: true
Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    - identifier: gallery
      name: Gallery
      title: Blog posts
      url: /gallery
      weight: 2
params:
  title: Hugo Profile - xxx yeeeey
  description: Text about my cool site
  favicon: /fav.png
  useBootstrapCDN: false
  animate: true
  theme: null
  font:
    fontSize: 1rem
    fontWeight: 400
    lineHeight: 1.5
    textAlign: left
  navbar:
    align: ms-auto
    brandName: Hugo Profile
    disableSearch: false
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false
  hero:
    enable: true
    intro: 'Hi, my name is'
    title: Bianca.
    subtitle: 'I am a good frontend developer, yes I ammmm'
    content: >-
      A passionate web app developer. I tend to make use of modern web
      technologies to build websites that looks great, feels fantastic, and
      functions correctly.
    image: /images/hero.svg
    button:
      enable: true
      name: Resume
      url: '#'
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: 'https://example.com'
        - icon: fab fa-twitter
          url: 'https://example.com'
      customIcons:
        - icon: /fav.png
          url: 'https://example.com'
  about:
    enable: true
    title: About Me
    image: /images/me.png
    content: >-
      I am a software developer with a passion for web development. I have a
      background in computer science and mathematics, and I have a strong
      interest in the intersection of technology and art. I am currently working
      as a software developer at [example org.](https://example.com) in San
      Francisco, CA. 


      I am currently working on a project that will be used to help people find
      the best way to get around the city.
    skills:
      enable: true
      title: 'Here are a few technologies I''ve been working with recently:'
      items:
        - Vue.js
        - Vuex
        - HTML
        - CSS
        - JavaScript
        - Git
        - Algorithms
        - Data Structures
        - Bootstrap
